Logging to shared log directory: /tmp/test_logs//1331872747
only running test 0a
excepting tests: 
mft01: Checking config lustre mounted on /mnt/lustre
Checking servers environments
Checking clients mft01 environments
Using TIMEOUT=20
disable quota as required
debug=0x33f0404
subsystem_debug=0xffb7e3ff
debug_mb=2
setting all flavor to null
already have total 5 null connections
/mnt/lustre/d0.replay-ost-single
stripe_count:   1 stripe_size:    1048576 stripe_offset:  0 

== replay-ost-single test 0a: target handle mismatch (bug 5317) 06:39:08 == 06:39:08 (1331872748)
Stopping client mft01 /mnt/lustre (opts:-f)
fail_loc=0x80000211
Starting client: mft01: -o user_xattr,acl,flock mft01@tcp:/lustre /mnt/lustre
debug=0x33f0404
subsystem_debug=0xffb7e3ff
debug_mb=2
Filesystem           1K-blocks      Used Available Use% Mounted on
mft01@tcp:/lustre       374928     49528    305400  14% /mnt/lustre
Resetting fail_loc on all nodes...done.
PASS 0a (11s)
........== replay-ost-single replay-ost-single.sh test complete, duration 12 sec == 06:39:19 (1331872759)
