Logging to shared log directory: /tmp/test_logs//1333468183
only running test 21a
excepting tests: 15c
Starting client mft02: -o user_xattr,acl,flock mft02@tcp:/lustre /mnt/lustre2
Started clients mft02: 
mft02@tcp:/lustre on /mnt/lustre2 type lustre (rw,user_xattr,acl,flock)
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
mft02: Checking config lustre mounted on /mnt/lustre
Checking servers environments
Checking clients mft02 environments
Using TIMEOUT=20
disable quota as required
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
setting all flavor to null
already have total 8 null connections
......................

== replay-dual test 21a: commit on sharing == 18:49:54 (1333468194)
mdt.lustre-MDT0000.commit_on_sharing=1
Replay barrier on lustre-MDT0000
Failing mds1 on node mft02
Stopping /mnt/mds1 (opts:) on mft02
affected facets: mds1
Failover mds1 to mft02
18:50:07 (1333468207) waiting for mft02 network 900 secs ...
18:50:07 (1333468207) network interface is UP
Starting mds1: -o loop,user_xattr,acl  /tmp/lustre-mdt1 /mnt/mds1
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
Started lustre-MDT0000
Starting client: mft02: -o user_xattr,acl,flock mft02@tcp:/lustre /mnt/lustre2
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
mdt.lustre-MDT0000.commit_on_sharing=0
Resetting fail_loc on all nodes...done.
PASS 21a (96s)
.== replay-dual replay-dual.sh test complete, duration 107 sec == 18:51:30 (1333468290)
Stopping clients: mft02 /mnt/lustre2 (opts:)
Stopping client mft02 /mnt/lustre2 opts:
