==> /tmp/serial_mft01_out <==
Lustre: DEBUG MARKER: only running test 0b
Lustre: DEBUG MARKER: excepting tests:
Lustre: DEBUG MARKER: Using TIMEOUT=20
Lustre: 2233:0:(quota_master.c:793:close_quota_files()) quota[0] is off already
Lustre: 2233:0:(quota_master.c:793:close_quota_files()) Skipped 1 previous similar message
LustreError: 5303:0:(quota_ctl.c:328:client_quota_ctl()) ptlrpc_queue_wait failed, rc: -114
Lustre: 5357:0:(debug.c:326:libcfs_debug_str2mask()) You are trying to use a numerical value for the mask - this will be deprecated in a future release.
Lustre: 5357:0:(debug.c:326:libcfs_debug_str2mask()) Skipped 3 previous similar messages
Lustre: DEBUG MARKER: == replay-ost-single test 0b: empty replay == 06:39:33 (1331872773)
Lustre: Failing over lustre-OST0000
LustreError: 2317:0:(ldlm_lib.c:2125:target_send_reply_msg()) @@@ processing error (-107)  req@ffff8800783a3c00 x1396569758761125/t0(0) o400-><?>@<?>:0/0 lens 192/0 e 0 to 0 dl 1331872779 ref 1 fl Interpret:H/0/ffffffff rc -107/-1
LustreError: 11-0: an error occurred while communicating with 0@lo. The obd_ping operation failed with -107
Lustre: lustre-OST0000-osc-ffff880074c42800: Connection to service lustre-OST0000 via nid 0@lo was lost; in progress operations using this service will wait for recovery to complete.
LustreError: 137-5: UUID 'lustre-OST0000_UUID' is not available  for connect (stopping)
Lustre: lustre-OST0000: shutting down for failover; client state will be preserved.
Lustre: OST lustre-OST0000 has stopped.
Lustre: server umount lustre-OST0000 complete
LustreError: 2317:0:(ldlm_lib.c:2125:target_send_reply_msg()) @@@ processing error (-107)  req@ffff880079714c00 x1396569758761129/t0(0) o400-><?>@<?>:0/0 lens 192/0 e 0 to 0 dl 1331872784 ref 1 fl Interpret:H/0/ffffffff rc -107/-1
LustreError: 2317:0:(ldlm_lib.c:2125:target_send_reply_msg()) Skipped 1 previous similar message
LustreError: 11-0: an error occurred while communicating with 0@lo. The obd_ping operation failed with -107
LustreError: Skipped 1 previous similar message
Lustre: lustre-OST0000-osc-MDT0000: Connection to service lustre-OST0000 via nid 0@lo was lost; in progress operations using this service will wait for recovery to complete.
LustreError: 137-5: UUID 'lustre-OST0000_UUID' is not available  for connect (no target)
Lustre: 1628:0:(import.c:526:import_select_connection()) lustre-OST0000-osc-ffff880074c42800: tried all connections, increasing latency to 10s
LustreError: 137-5: UUID 'lustre-OST0000_UUID' is not available  for connect (no target)
LustreError: 2317:0:(ldlm_lib.c:2125:target_send_reply_msg()) @@@ processing error (-19)  req@ffff880037efb800 x1396569758761137/t0(0) o8-><?>@<?>:0/0 lens 368/0 e 0 to 0 dl 1331872803 ref 1 fl Interpret:/0/ffffffff rc -19/-1
LustreError: 2317:0:(ldlm_lib.c:2125:target_send_reply_msg()) Skipped 1 previous similar message
LustreError: 11-0: an error occurred while communicating with 0@lo. The ost_connect operation failed with -19
LustreError: Skipped 1 previous similar message
LDISKFS-fs (loop1): mounted filesystem with ordered data mode
LDISKFS-fs (loop1): mounted filesystem with ordered data mode
Lustre: 5703:0:(ldlm_lib.c:1900:target_recovery_init()) RECOVERY: service lustre-OST0000, 3 recoverable clients, last_transno 0
LustreError: 5704:0:(ldlm_lib.c:1737:target_recovery_thread()) lustre-OST0000: started recovery thread pid 5704
Lustre: 5703:0:(filter.c:1252:filter_prep_groups()) lustre-OST0000: initialize groups [0,0]
Lustre: lustre-OST0000: Now serving lustre-OST0000 on /dev/loop1 with recovery enabled
Lustre: lustre-OST0000: Will be in recovery for at least 1:00, or until 3 clients reconnect
LustreError: 5695:0:(obd_class.h:1622:obd_notify()) obd lustre-OST0000 has no notify handler
Lustre: 1628:0:(import.c:526:import_select_connection()) lustre-OST0000-osc-MDT0000: tried all connections, increasing latency to 6s
Lustre: 2317:0:(ldlm_lib.c:873:target_handle_connect()) lustre-OST0000: connection from lustre-MDT0000-mdtlov_UUID@0@lo recovering/t0 exp ffff88007971b000 cur 1331872788 last 1331872787
Lustre: 2317:0:(filter.c:2710:filter_connect_internal()) lustre-OST0000: Received MDS connection for group 0
Lustre: 2320:0:(sec.c:1474:sptlrpc_import_sec_adapt()) import lustre-OST0000->NET_0x9000000000000_UUID netid 90000: select flavor null
Lustre: lustre-OST0001: haven't heard from client cbc05f3d-7ab3-4dd4-b63c-38cd0ad4a2e2 (at 0@lo) in 54 seconds. I think it's dead, and I am evicting it. exp ffff880078992c00, cur 1331872798 expire 1331872768 last 1331872744
Lustre: 5704:0:(ldlm_lib.c:1566:target_recovery_overseer()) recovery is timed out, evict stale exports
LustreError: 5704:0:(genops.c:1270:class_disconnect_stale_exports()) lustre-OST0000: disconnect stale client cbc05f3d-7ab3-4dd4-b63c-38cd0ad4a2e2@<unknown>
Lustre: lustre-OST0000-osc-ffff880074c42800: Connection restored to service lustre-OST0000 using nid 0@lo.
Lustre: lustre-OST0000: sending delayed replies to recovered clients
Lustre: lustre-OST0000-osc-MDT0000: Connection restored to service lustre-OST0000 using nid 0@lo.
Lustre: lustre-OST0000: received MDS connection from 0@lo
Lustre: MDS mdd_obd-lustre-MDT0000: lustre-OST0000_UUID now active, resetting orphans
Lustre: DEBUG MARKER: == replay-ost-single replay-ost-single.sh test complete, duration 83 sec == 06:40:55 (1331872855)
