==> /var/log/messages <==
Apr  3 17:54:50 mft03 kernel: Lustre: DEBUG MARKER: only running test 6
Apr  3 17:54:50 mft03 kernel: Lustre: DEBUG MARKER: excepting tests:
Apr  3 17:54:50 mft03 kernel: Lustre: DEBUG MARKER: Using TIMEOUT=20
Apr  3 17:54:51 mft03 kernel: Lustre: DEBUG MARKER: == replay-ost-single test 6: Fail OST before obd_destroy == 17:54:51 (1333464891)
Apr  3 17:55:00 mft03 kernel: Lustre: DEBUG MARKER: before: 325400 after_dd: 320280
Apr  3 17:55:00 mft03 kernel: LustreError: 2196:0:(libcfs_fail.h:81:cfs_fail_check_set()) *** cfs_fail_loc=119 ***
Apr  3 17:55:00 mft03 kernel: LustreError: 2196:0:(ldlm_lib.c:2120:target_send_reply_msg()) @@@ dropping reply  req@ffff88007a372850 x1398238915593090/t4294967443(0) o36->6feb199b-758a-d2fa-2399-c706241609fc@0@lo:0/0 lens 456/544 e 0 to 0 dl 1333464906 ref 1 fl Interpret:/0/0 rc 0/0
Apr  3 17:55:07 mft03 kernel: Lustre: 16375:0:(client.c:1773:ptlrpc_expire_one_request()) @@@ Request  sent has timed out for slow reply: [sent 1333464900/real 1333464900]  req@ffff88007817c800 x1398238915593090/t0(0) o36->lustre-MDT0000-mdc-ffff880037540800@0@lo:12/10 lens 456/824 e 0 to 1 dl 1333464907 ref 2 fl Rpc:X/0/ffffffff rc 0/-1
Apr  3 17:55:07 mft03 kernel: Lustre: lustre-MDT0000-mdc-ffff880037540800: Connection to service lustre-MDT0000 via nid 0@lo was lost; in progress operations using this service will wait for recovery to complete.
Apr  3 17:55:07 mft03 kernel: Lustre: Skipped 1 previous similar message
Apr  3 17:55:07 mft03 kernel: Lustre: 2196:0:(ldlm_lib.c:605:target_handle_reconnect()) lustre-MDT0000: 6feb199b-758a-d2fa-2399-c706241609fc reconnecting
Apr  3 17:55:07 mft03 kernel: Lustre: 2196:0:(ldlm_lib.c:873:target_handle_connect()) lustre-MDT0000: connection from 6feb199b-758a-d2fa-2399-c706241609fc@0@lo t4294967438 exp ffff88007c78ec00 cur 1333464907 last 1333464907
Apr  3 17:55:07 mft03 kernel: Lustre: 2196:0:(ldlm_lib.c:873:target_handle_connect()) Skipped 3 previous similar messages
Apr  3 17:55:07 mft03 kernel: Lustre: lustre-MDT0000-mdc-ffff880037540800: Connection restored to service lustre-MDT0000 using nid 0@lo.
Apr  3 17:55:07 mft03 kernel: Lustre: Skipped 1 previous similar message
Apr  3 17:55:07 mft03 kernel: Lustre: Failing over lustre-OST0000
Apr  3 17:55:09 mft03 kernel: Lustre: lustre-OST0000: shutting down for failover; client state will be preserved.
Apr  3 17:55:09 mft03 kernel: Lustre: OST lustre-OST0000 has stopped.
Apr  3 17:55:12 mft03 kernel: Lustre: server umount lustre-OST0000 complete
Apr  3 17:55:12 mft03 kernel: LustreError: 2281:0:(ldlm_lib.c:2125:target_send_reply_msg()) @@@ processing error (-107)  req@ffff8800775b2000 x1398238915593098/t0(0) o400-><?>@<?>:0/0 lens 192/0 e 0 to 0 dl 1333464937 ref 1 fl Interpret:H/0/ffffffff rc -107/-1
Apr  3 17:55:12 mft03 kernel: LustreError: 2281:0:(ldlm_lib.c:2125:target_send_reply_msg()) Skipped 3 previous similar messages
Apr  3 17:55:12 mft03 kernel: LustreError: 11-0: an error occurred while communicating with 0@lo. The obd_ping operation failed with -107
Apr  3 17:55:12 mft03 kernel: LustreError: Skipped 3 previous similar messages
Apr  3 17:55:12 mft03 kernel: LustreError: 137-5: UUID 'lustre-OST0000_UUID' is not available  for connect (no target)
Apr  3 17:55:12 mft03 kernel: LustreError: Skipped 1 previous similar message
Apr  3 17:55:22 mft03 kernel: Lustre: 1609:0:(import.c:526:import_select_connection()) lustre-OST0000-osc-MDT0000: tried all connections, increasing latency to 21s
Apr  3 17:55:22 mft03 kernel: Lustre: 1609:0:(import.c:526:import_select_connection()) Skipped 1 previous similar message
Apr  3 17:55:22 mft03 kernel: LDISKFS-fs (loop1): mounted filesystem with ordered data mode
Apr  3 17:55:22 mft03 kernel: LDISKFS-fs (loop1): mounted filesystem with ordered data mode
Apr  3 17:55:22 mft03 kernel: Lustre: 16539:0:(ldlm_lib.c:1900:target_recovery_init()) RECOVERY: service lustre-OST0000, 2 recoverable clients, last_transno 41
Apr  3 17:55:22 mft03 kernel: LustreError: 16540:0:(ldlm_lib.c:1737:target_recovery_thread()) lustre-OST0000: started recovery thread pid 16540
Apr  3 17:55:22 mft03 kernel: Lustre: 16539:0:(filter.c:1252:filter_prep_groups()) lustre-OST0000: initialize groups [0,0]
Apr  3 17:55:22 mft03 kernel: Lustre: lustre-OST0000: Now serving lustre-OST0000 on /dev/loop1 with recovery enabled
Apr  3 17:55:22 mft03 kernel: Lustre: lustre-OST0000: Will be in recovery for at least 1:00, or until 2 clients reconnect
Apr  3 17:55:22 mft03 kernel: LustreError: 16531:0:(obd_class.h:1622:obd_notify()) obd lustre-OST0000 has no notify handler
Apr  3 17:55:22 mft03 kernel: Lustre: 16555:0:(debug.c:326:libcfs_debug_str2mask()) You are trying to use a numerical value for the mask - this will be deprecated in a future release.
Apr  3 17:55:22 mft03 kernel: Lustre: 16555:0:(debug.c:326:libcfs_debug_str2mask()) Skipped 11 previous similar messages
Apr  3 17:55:32 mft03 kernel: Lustre: 2282:0:(filter.c:2710:filter_connect_internal()) lustre-OST0000: Received MDS connection for group 0
Apr  3 17:55:32 mft03 kernel: Lustre: lustre-OST0000: sending delayed replies to recovered clients
Apr  3 17:55:32 mft03 kernel: Lustre: lustre-OST0000-osc-MDT0000: Connection restored to service lustre-OST0000 using nid 0@lo.
Apr  3 17:55:32 mft03 kernel: Lustre: lustre-OST0000: received MDS connection from 0@lo
Apr  3 17:55:32 mft03 kernel: Lustre: 2283:0:(filter.c:2566:filter_llog_connect()) lustre-OST0000: Recovery from log 0x1f/0x0:e896bf9c
Apr  3 17:55:32 mft03 kernel: Lustre: MDS mdd_obd-lustre-MDT0000: lustre-OST0000_UUID now active, resetting orphans
Apr  3 17:55:36 mft03 kernel: Lustre: DEBUG MARKER: before: 325400 after: 325400
Apr  3 17:55:36 mft03 kernel: Lustre: DEBUG MARKER: == replay-ost-single replay-ost-single.sh test complete, duration 46 sec == 17:55:36 (1333464936)
