Logging to shared log directory: /tmp/test_logs//1331863858
only running test 13
excepting tests: 15c
Starting client mft01: -o user_xattr,acl,flock mft01@tcp:/lustre /mnt/lustre2
Started clients mft01: 
mft01@tcp:/lustre on /mnt/lustre2 type lustre (rw,user_xattr,acl,flock)
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
mft01: Checking config lustre mounted on /mnt/lustre
Checking servers environments
Checking clients mft01 environments
Using TIMEOUT=20
disable quota as required
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
setting all flavor to null
already have total 8 null connections
.............

== replay-dual test 13: close resend timeout == 04:11:10 (1331863870)
multiop /mnt/lustre/f13 vmo_c
TMPPIPE=/tmp/multiop_open_wait_pipe.28788
Filesystem           1K-blocks      Used Available Use% Mounted on
mft01@tcp:/lustre       374928     49528    305272  14% /mnt/lustre
fail_loc=0x80000115
Failing mds1 on node mft01
Stopping /mnt/mds1 (opts:) on mft01
affected facets: mds1
Failover mds1 to mft01
04:11:23 (1331863883) waiting for mft01 network 900 secs ...
04:11:23 (1331863883) network interface is UP
Starting mds1: -o loop,user_xattr,acl  /tmp/lustre-mdt1 /mnt/mds1
debug=-1
subsystem_debug=0xffb7e3ff
debug_mb=2
Started lustre-MDT0000
fail_loc=0
/mnt/lustre/f13
/mnt/lustre/f13 has type file OK
Resetting fail_loc on all nodes...done.
PASS 13 (19s)
..........== replay-dual replay-dual.sh test complete, duration 31 sec == 04:11:29 (1331863889)
Stopping clients: mft01 /mnt/lustre2 (opts:)
Stopping client mft01 /mnt/lustre2 opts:
